--- #YAML:1.0
name:               MogileFS-Server
version:            2.51
abstract:           MogileFS (distributed filesystem) server
author:
    - Brad Fitzpatrick <brad@danga.com>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Danga::Socket:     1.56
    DBI:               0
    fields:            0
    Getopt::Long:      0
    IO::AIO:           0
    MogileFS::Client:  0
    Net::Netmask:      0
    Perlbal:           1.79
    Symbol:            0
    Sys::Syscall:      0.22
    Sys::Syslog:       0
resources:
    bugtracker:   http://code.google.com/p/mogilefs/issues/list
    homepage:     http://www.mogilefs.org
    MailingList:  http://groups.google.com/group/mogile
    repository:   git://github.com/mogilefs/MogileFS-Server.git
no_index:
    directory:
        - t
        - inc
        - lib/mogdeps
    package:
        - ProcessHandle
        - TrackerHandle
        - MogstoredHandle
        - MogPath
        - Mgd
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
